firstapp/firstapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('', include('home.urls')),
    path('mbk/', include('mbk.urls')),
    path('poll/', include('polls.urls')),
]

firstapp/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home),
    path('info/', views.show_info),
]

firstapp/mbk/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.list_theory),
    path('mbkdetail/<int:theory_id>', views.detail_theory_mbk),
]

firstapp/polls/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.list_poll),
    path('polldetail/<int:question_id>', views.detail_question_poll),
               ]

firstapp/home/models.py
from django.db import models

# Create your models here.

firstapp/mbk/models.py
from django.db import models


# Create your models here.
class Theory(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class SupportiveFact(models.Model):
    theory = models.ForeignKey(Theory, on_delete=models.CASCADE)
    description = models.TextField()

firstapp/polls/models.py
from django.db import models


# Create your models here.
class Question(models.Model):
    title = models.CharField(max_length=255, default='Untitled')
    question = models.TextField()
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()

    def __str__(self):
        return self.title


class Option(models.Model):
    id_question = models.ForeignKey(Question, on_delete=models.CASCADE)
    option = models.TextField()

firstapp/home/views.py
from django.http import HttpResponse
from django.shortcuts import render
from ip3country import CountryLookup


# Create your views here.

def say_hello(request):
    return HttpResponse('Hello World Django')


def home(request):
    return render(request, 'home.html', {'wellcome': 'حای سلام دوستان خوش آمدید '})


def browser_info(request):
    user_agent = request.META.get('HTTP_USER_AGENT', '')
    return render(request, 'browser_info.html', {'browser_name': user_agent})


def ip_user(request):
    user_info = request.META.get('REMOTE_ADDR')
    return render(request, 'browser_info.html', {'browser_ip': user_info})


def show_info(request):
    user_agent = request.META.get('HTTP_USER_AGENT', '')
    user_ip = request.META.get('REMOTE_ADDR')
    # user_ip = '159.146.73.217'
    lookup = CountryLookup()
    country_code = lookup.lookupStr(user_ip)
    data = {
        'browser_name': user_agent, 'user_ip': user_ip, 'country_code': country_code,
    }

    return render(request, 'browser_info.html', data)


def detail_browser(request, browser_inf):
    inf = show_info.objects.get(browser_inf)
    return render(request, 'browser_detail.html', {'user_inf': inf})

firstapp/mbk/views.py
from django.shortcuts import render
from .models import Theory
from django.db import models


# Create your views here.


def list_theory(request):
    theories = Theory.objects.all()
    print(theories)
    return render(request, 'theory_list.html', {'all_theory': theories})


def detail_theory_mbk(request, theory_id):
    theo = Theory.objects.get(id=theory_id)
    return render(request, 'theory_detail.html', {'theory_select': theo})

firstapp/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Question
from datetime import datetime


def say_hello(request):
    return HttpResponse('Hello poll')


def template_poll(request):
    return render(request, 'poll_info.html')


current_datetime = datetime.now()


def list_poll(request):
    question = Question.objects.filter(start_date__lte=current_datetime, end_date__gte=current_datetime)
    # print(question)
    return render(request, 'poll_info.html', {'all_questions': question})


def detail_question_poll(request, question_id):
    qsn = Question.objects.get(id=question_id)
    return render(request, 'poll_detail.html', {'question_select': qsn})

firstapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
        <style>
        html, body {
            direction: rtl;
            text-align: right;
        }
        .jumbotron{
            padding: 20px;
            margin-bottom: 20px;
            background-color: #e9ecef;
        }
            .sidenav {

              height: 100%;
              width: 260px;
              position: fixed;
              z-index: 1;
              top: 50;
              right: 0;
              background-color:  #2e4053 ;
              overflow-x: hidden;
              padding-top: 20px;
            }

            .sidenav a {
              padding: 6px 28px 6px 16px;
              text-decoration: none;
              font-size: 25px;
              color: #818181;
              display: block;
            }

            .sidenav a:hover {
              color: #f1f1f1;
            }

            .main {
              margin-right: 360px; /* Same as the width of the sidenav */
              font-size: 28px; /* Increased text to enable scrolling */
              padding: 30px 10px;
            }

            @media screen and (max-height: 450px) {
              .sidenav {padding-top: 15px;}
              .sidenav a {font-size: 18px;}
            }
    </style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

</head>
<body>
    {% include 'navbar.html' %}
    {% include 'sidebar-right.html' %}
    <div class="main">
      {% block content %}  {% endblock %}
    </div>
</body>
</html>

firstapp/templates/browser_info.html
{% extends 'base.html' %}

{% block content %}

        <p>نسخه های مرورگر شما :<br> {{ browser_name }}</p>
        <p>آدرس آی پی شما : {{ user_ip }}</p>
        <p>کشور شما : {{ country_code }}</p>

{% endblock %}

firstapp/templates/home.html
{% extends 'base.html' %}

{% block content %}

    <h2>  {{ wellcome }}</h2>

{% endblock %}

firstapp/templates/navbar.html
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/home">خانه</a>
      </div>
    </nav>

firstapp/templates/poll_detail.html
{% extends 'base.html' %}

{% block content %}

  <h2> {{ question_select.question }} </h2>
  <h6> {{ question_select.start_date }} </h6>
  <h6> {{ question_select.end_date }} </h6>

      <ul>
          {% for item in question_select.option_set.all %}
          <li> {{ item.option }}</li>
          {% endfor %}
      </ul>

{% endblock %}

firstapp/templates/poll_info.html
{% extends 'base.html' %}

{% block title %} Poll {% endblock %}

{% block content %}

    <h1>نظر سنجی ها </h1>
        <ol>
            {% for poll in all_questions %}
                <li>
                    <h3><a href="polldetail/{{ poll.id }}"> {{ poll.question }} </a></h3>
                </li>
            {% endfor %}
        </ol>

{% endblock %}

firstapp/templates/sidebar-right.html
 <!-- Side navigation -->
<div class="sidenav">
  <a href="/info">اطلاعات سیستم</a>
  <a href="/mbk">سوتراها</a>
  <a href="/poll">نظرسنجی ها</a>
</div>

firstapp/templates/theory_detail.html
{% extends 'base.html' %}

{% block content %}

  <h2> {{ theory_select.title }} </h2>
  <h3> {{ theory_select.description }} </h3>
  <h6> {{ theory_select.created_at }} </h6>

      <ul>
          {% for item in theory_select.description_set.all %}
          <li> {{ item.description }}</li>
          {% endfor %}
      </ul>

{% endblock %}

firstapp/templates/theory_list.html
{% extends 'base.html' %}

{% block title %} Theory {% endblock %}

{% block content %}

    <h1>لیست تیوری ها</h1>
    <ul>
        <ol>
            {% for item in all_theory %}
                <li>
                    <h3><a href="mbkdetail/{{ item.id }}"> {{ item.description }} </a></h3>
                </li>
            {% endfor %}
        </ol>
    </ul>

{% endblock %}